global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "gotify-notifications"

receivers:
  - name: "gotify-notifications"
    webhook_configs:
      - url: "http://gotify:80/message"
        send_resolved: true
        http_config:
          bearer_token: "AQk_Kndp2CkP48F"
