services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - grafana_dir:/var/lib/grafana
    networks:
      - monitoring_network

  loki:
    container_name: loki
    image: grafana/loki:3.4.1
    volumes:
      - ./config:/mnt/config
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - monitoring_network

  promtail:
    container_name: promtail
    image: grafana/promtail:3.4.1
    networks:
      - monitoring_network
    volumes:
      - ./config:/mnt/config
    ports:
      - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/mnt/config/promtail-config.yaml
    depends_on:
      - loki

networks:
  monitoring_network:
    external: true
volumes:
  grafana_dir:
  loki_dir:
  promtail_dir:
