---
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - TZ=Africa/Kenya
    volumes:
      - calibre_dir:/config
    ports:
      - 8085:8080
      - 8181:8181
      - 8082:8081
    restart: unless-stopped

volumes:
  calibre_dir:
