---
services:
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - TZ=Africa/Kenya
    volumes:
      - mylar3_dir:/config
      - /mnt/shared/media/books:/comics
      - /mnt/shared/media/downloads:/downloads
    ports:
      - "8090:8090"
    restart: unless-stopped
    networks:
      downloader_network:

networks:
  downloader_network:
    external: true

volumes:
  mylar3_dir:
