services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./config:/etc/prometheus
      - prometheus_dir:/prometheus
    networks:
      - monitoring_network

networks:
  monitoring_network:
    external: true
volumes:
  prometheus_dir:
