- Prime:
    - Homeassistant:
        href: "https://my.home.brianphiri.online"
        icon: https://raw.githubusercontent.com/home-assistant/frontend/dev/static/icons/favicon-192x192.png
        widget:
          type: homeassistant
          url: "https://my.home.brianphiri.online"
          key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwZTZkYjUyYzFlZGM0NzY0OTg2ZDY1YzgyY2EyNTA5ZCIsImlhdCI6MTc0MDgxNzQwNCwiZXhwIjoyMDU2MTc3NDA0fQ.3dr85snDDyaBTtvDsRfKot-xyvTALAEIEFV-RXFSkqM
          custom:
            - state: sensor.total_power
            - state: sensor.total_energy_today
              label: energy today
            - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
              label: switches on
            - state: weather.forecast_home
              label: wind speed
              value: "{attributes.wind_speed} {attributes.wind_speed_unit}"
    - Portainer:
        href: "https://portainer.home.brianphiri.online"
        icon: ""
        widget:
          type: portainer
          url: https://portainer.home.brianphiri.online
          env: 1
          key: ptr_lCtztKbNksXEZvvbDdFu8LQoY+D69rFwJVkS0wwMvyc=

- Media:
    - JellyFin:
        href: "https://jellyfin.home.brianphiri.online"
        icon: https://jellyfin.org/images/logo.svg
        widget:
          type: jellyfin
          icon: "https://jellyfin.org/images/logo.svg"
          url: https://jellyfin.home.brianphiri.online
          key: def49f17c08d43d8867a451742321a8f
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true
    - Jellyseerr:
        href: "https://jellyseerr.home.brianphiri.online"
        icon: https://raw.githubusercontent.com/Fallenbagel/jellyseerr/develop/public/android-chrome-512x512.png
        widget:
          type: jellyseerr
          url: http://jellyseerr.host.or.ip
          key: MTc0MDMyMDA2OTY4M2U4ZWMwYWY5LWE3ZmUtNDA3ZC1hMTRlLWYxNTgyMjA5MDE0ZQ==
    - Kavita:
        href: "https://kavita.home.brianphiri.online"
        widget:
          type: kavita
          url: https://kavita.home.brianphiri.online
          username: brian
          password: kavita
    - Calibre:
        href: "https://calibre.home.brianphiri.online"
        widget:
          type: calibreweb
          url: https://calibre.home.brianphiri.online
          username: username
          password: password

- Downloader:
    - QtTorrent:
        href: "https://torrent.home.brianphiri.online"
        icon: https://upload.wikimedia.org/wikipedia/commons/6/66/New_qBittorrent_Logo.svg
        widget:
          type: qbittorrent
          url: https://torrent.home.brianphiri.online
          username: brian
          password: qbittorent
          enableLeechProgress: true # optional, defaults to false
    - Sonarr:
        icon: https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/128.png
        href: "https://sonarr.home.brianphiri.online"
        widget:
          type: sonarr
          url: https://sonarr.home.brianphiri.online
          key: 2ffeec8edd954477a230f189d2352863
          enableQueue: true # optional, defaults to false
    - Radarr:
        href: "https://radarr.home.brianphiri.online"
        icon: https://raw.githubusercontent.com/Radarr/Radarr/develop/Logo/128.png
        widget:
          type: radarr
          url: https://radarr.home.brianphiri.online
          key: 85ccbde2b40d453193be3b8f31e6be41
          enableQueue: true # optional, defaults to false
    - Readarr:
        href: "https://readarr.home.brianphiri.online"
        icon: https://raw.githubusercontent.com/Readarr/Readarr/develop/Logo/128.png
        widget:
          type: readarr
          url: https://readarr.home.brianphiri.online
          key: c56c08646a8248f5ba801a2c6235bb4a
    - Prowlarr:
        href: "https://prowlarr.home.brianphiri.online"
        icon: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/128.png
        widget:
          type: prowlarr
          url: https://prowlarr.home.brianphiri.online
          key: 00d56c944625483c8c70e6a17539c6f5

- Network:
    - Adguard:
        href: "https://prowlarr.home.brianphiri.online"
        icon: https://adguard.com/img/adguard.ico
        widget:
          type: adguard
          url: https://prowlarr.home.brianphiri.online
          username: admin
          password: adgaurd
    - Consul:
        href: "https://prowlarr.home.brianphiri.online"
        icon: https://raw.githubusercontent.com/hashicorp/consul/main/website/public/img/favicon.ico
    - Traefik:
        href: "https://traefik.home.brianphiri.online"
        icon: https://github.com/traefik/traefik/raw/master/docs/content/assets/img/traefik.logo.png
        widget:
          type: traefik
          url: https://traefik.home.brianphiri.online

- Monitoring:
    - Grafana:
        href: "https://grafana.home.brianphiri.online"
        icon: https://grafana.com/static/img/menu/grafana2.svg
        widget:
          type: grafana
          url: https://grafana.home.brianphiri.online
          username: admin
          password: grafana
    - Prometheus:
        href: "https://prometheus.home.brianphiri.online"
        icon: https://prometheus.io/assets/favicons/favicon.ico
        widget:
          type: prometheus
          url: https://prometheus.home.brianphiri.online
