---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Africa/Kenya
    volumes:
      - sonarr_dir:/config
      - /mnt/shared/media/tvseries:/tv #optional
      - /mnt/shared/downloadclient-downloads:/downloads #optional
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - downloader_network
      - oversee_network

networks:
  downloader_network:
    external: true
  oversee_network:
    external: true

volumes:
  sonarr_dir:
