services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Africa/Kenya
    ports:
      - "5055:5055"
    volumes:
      - jellyseerr_dir:/app/config
    restart: unless-stopped

volumes:
  jellyseerr_dir:
