---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Kenya
    volumes:
      - prowlarr_dir:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      downloader_network:

networks:
  downloader_network:
    external: true

volumes:
  prowlarr_dir:
