services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Nairobi
    volumes:
      - freshrss_dir:/config
    ports:
      - 80:80
    restart: unless-stopped

volumes:
  freshrss_dir:
