# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  opentofu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenTofu
        run: |
          curl -sSfL https://github.com/opentofu/opentofu/releases/latest/download/tofu_linux_amd64.tar.gz | tar -xz
          sudo mv tofu /usr/local/bin/
      - name: OpenTofu Format
        run: tofu fmt -check -recursive tf/
      - name: OpenTofu Validate
        run: tofu validate tf/
      - name: TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Run TFLint
        run: tflint tf/
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: tf/

  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ansible
        run: pip install ansible ansible-lint
      - name: Ansible Lint
        run: ansible-lint playbook.yml
      - name: Ansible Syntax Check
        run: ansible-playbook --syntax-check playbook.yml
