# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Format
        run: terraform fmt -check -recursive tf/
      - name: Terraform Validate
        run: terraform validate tf/
      - name: TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Run TFLint
        run: tflint tf/
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: tf/
